/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.freasearch.search

import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*

import org.freasearch.search.logger.*
import org.freasearch.search.router.*


class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    msg_info("DEBUG LOG")
    msg_error("DEBUG ERROR")
    msg_warn("DEBUG WARN")
    embeddedServer(Netty, port = 8080, host = "0.0.0.0", module = Application::module)
        .start(wait = true)
}

fun Application.module() {
    configureRouting()
}
